-- Manual/provisional quotes and order statuses prepared for Google Maps later.

ALTER TYPE "ORDERS"."STATUS_ORDERS" ADD VALUE IF NOT EXISTS 'PENDING_QUOTE';
ALTER TYPE "ORDERS"."STATUS_ORDERS" ADD VALUE IF NOT EXISTS 'PENDING_CUSTOMER_CONFIRMATION';
ALTER TYPE "ORDERS"."STATUS_ORDERS" ADD VALUE IF NOT EXISTS 'PENDING_PAYMENT';
ALTER TYPE "ORDERS"."STATUS_ORDERS" ADD VALUE IF NOT EXISTS 'CONFIRMED';
ALTER TYPE "ORDERS"."STATUS_ORDERS" ADD VALUE IF NOT EXISTS 'ASSIGNING_DRIVER';

CREATE TYPE "PRICES"."QUOTE_SOURCE" AS ENUM ('MANUAL', 'GOOGLE_MAPS');
CREATE TYPE "PRICES"."QUOTE_STATUS" AS ENUM ('DRAFT', 'PROVISIONAL', 'CALCULATED', 'SENT', 'ACCEPTED', 'REJECTED', 'EXPIRED', 'REPLACED');

ALTER TABLE "PRICES"."price_quotes"
  ADD COLUMN "order_id" TEXT,
  ADD COLUMN "quote_source" "PRICES"."QUOTE_SOURCE" NOT NULL DEFAULT 'MANUAL',
  ADD COLUMN "quote_status" "PRICES"."QUOTE_STATUS" NOT NULL DEFAULT 'PROVISIONAL',
  ADD COLUMN "breakdown" JSONB,
  ADD COLUMN "manual_adjustment_amount" DECIMAL(65,30) NOT NULL DEFAULT 0,
  ADD COLUMN "adjustment_reason" TEXT,
  ADD COLUMN "adjusted_by" TEXT;

CREATE INDEX "price_quotes_order_id_idx" ON "PRICES"."price_quotes"("order_id");
CREATE INDEX "price_quotes_quote_status_idx" ON "PRICES"."price_quotes"("quote_status");

ALTER TABLE "PRICES"."price_quotes" ADD CONSTRAINT "price_quotes_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "ORDERS"."TransportOrders"("id") ON DELETE SET NULL ON UPDATE CASCADE;
