export const ERROR_CODES = {
  UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  INVALID_REFRESH_TOKEN: 'AUTH_INVALID_REFRESH_TOKEN',
  SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED',
  SESSION_REVOKED: 'AUTH_SESSION_REVOKED',
  TOKEN_REUSE_DETECTED: 'AUTH_TOKEN_REUSE_DETECTED',
  ACCOUNT_INACTIVE: 'AUTH_ACCOUNT_INACTIVE',
  ACCOUNT_BLOCKED: 'AUTH_ACCOUNT_BLOCKED',
  FORBIDDEN: 'FORBIDDEN',
  FORBIDDEN_ROLE: 'FORBIDDEN_ROLE',
  FORBIDDEN_PERMISSION: 'FORBIDDEN_PERMISSION',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  BAD_REQUEST: 'BAD_REQUEST',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  RESOURCE_CONFLICT: 'RESOURCE_CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  DOMAIN_RULE_VIOLATION: 'DOMAIN_RULE_VIOLATION',
  INTERNAL_ERROR: 'INTERNAL_ERROR',

  // Upstream (third-party) failures. Kept distinct from INTERNAL_ERROR so the
  // clients can tell "we are broken" from "the provider is unreachable".
  UPSTREAM_ERROR: 'UPSTREAM_ERROR',
  UPSTREAM_TIMEOUT: 'UPSTREAM_TIMEOUT',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',

  /**
   * Google answered but refused the call: billing not enabled on the Cloud
   * project, the API not activated, or the key restricted. It is a
   * configuration problem on our side, never the caller's.
   */
  MAPS_PROVIDER_DENIED: 'MAPS_PROVIDER_DENIED',
  MAPS_PROVIDER_QUOTA_EXCEEDED: 'MAPS_PROVIDER_QUOTA_EXCEEDED',
  MAPS_PROVIDER_UNAVAILABLE: 'MAPS_PROVIDER_UNAVAILABLE',
  ROUTE_PROVIDER_UNAVAILABLE: 'ROUTE_PROVIDER_UNAVAILABLE',
  /** Google answered fine, but there is no drivable route between the stops. */
  ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
